### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by Twi5TeD** [knightzmc/PrivateMines#36]
C:\Users\Michael\Desktop\PrivateMines-master>gradlew build

> Task :base:compileJava
C:\Users\Michael\Desktop\PrivateMines-master\base\src\main\java\me\bristermitten\privatemines\data\citizens\ultraprisoncore\UltraPrisonListener.java:10: error: package me.drawethree.ultraprisoncore.api.events does not exist
import me.drawethree.ultraprisoncore.api.events.UltraPrisonSellAllEvent;
                                               ^
C:\Users\Michael\Desktop\PrivateMines-master\base\src\main\java\me\bristermitten\privatemines\data\citizens\ultraprisoncore\UltraPrisonListener.java:78: error: cannot find symbol
    public void onUPCSellAllEvent(UltraPrisonSellAllEvent e) {
                                  ^
  symbol:   class UltraPrisonSellAllEvent
  location: class UltraPrisonListener
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

> Task :base:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
1 actionable task: 1 executed

**Comment by knightzmc** [comment]
Unfortunately you'll need to get an UltraPrisonCore jar that you can add to the libs folder.
As it's a premium plugin we can't really commit a working jar, and afaik there's no dedicated API jar.
No real way around this on our end, sorry for the inconvenience :/

**Comment by Twi5TeD** [comment]
i thought you can just use autosell instead of ultraprisoncore?

**Comment by UntouchedOdin0** [comment]
@Twi5TeD You can use autosell instead of ultraprisoncore. But you need to have both jars on hand to compile the code. The only way you can get around this is either buying UPC or purchasing the plugin from spigot and it'll be prebuilt for you. :)
