### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Minebender9** [knightzmc/PrivateMines#40]
Error when trying to build master branch with gradle

BUILD FAILED in 1m 37s

------

> Build starts at 2024-03-10 22:47:27
Start to build: :plugin:testClasses :plugin:classes
Task :base:compileJava started
Task :base:compileJava failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base:compileJava'.
> Could not resolve all files for configuration ':base:compileClasspath'.
   > Could not resolve net.citizensnpcs:citizens:2.0.25-SNAPSHOT.
     Required by:
         project :base
      > Could not resolve net.citizensnpcs:citizens:2.0.25-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.sk89q.com/repo/net/citizensnpcs/citizens/2.0.25-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://maven.sk89q.com/repo/net/citizensnpcs/citizens/2.0.25-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://maven.sk89q.com/repo/net/citizensnpcs/citizens/2.0.25-SNAPSHOT/maven-metadata.xml'.
                  > Read timed out
   > Could not resolve me.clip:placeholderapi:2.10.9.
     Required by:
         project :base
      > Could not resolve me.clip:placeholderapi:2.10.9.
         > Could not get resource 'https://maven.sk89q.com/repo/me/clip/placeholderapi/2.10.9/placeholderapi-2.10.9.pom'.
            > Could not HEAD 'https://maven.sk89q.com/repo/me/clip/placeholderapi/2.10.9/placeholderapi-2.10.9.pom'.
               > Read timed out
   > Could not resolve com.boydti:fawe-api:latest.
     Required by:
         project :base
      > Could not resolve com.boydti:fawe-api:latest.
         > Could not get resource 'https://maven.sk89q.com/repo/com/boydti/fawe-api/latest/fawe-api-latest.pom'.
            > Could not GET 'https://maven.sk89q.com/repo/com/boydti/fawe-api/latest/fawe-api-latest.pom'.
               > Read timed out
   > Could not resolve com.sk89q.worldedit:worldedit-bukkit:6.1.4-SNAPSHOT.
     Required by:
         project :base
      > Could not resolve com.sk89q.worldedit:worldedit-bukkit:6.1.4-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.sk89q.com/repo/com/sk89q/worldedit/worldedit-bukkit/6.1.4-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://maven.sk89q.com/repo/com/sk89q/worldedit/worldedit-bukkit/6.1.4-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://maven.sk89q.com/repo/com/sk89q/worldedit/worldedit-bukkit/6.1.4-SNAPSHOT/maven-metadata.xml'.
                  > Read timed out
   > Could not resolve com.sk89q.worldguard:worldguard-bukkit:7.0.2.
     Required by:
         project :base
      > Could not resolve com.sk89q.worldguard:worldguard-bukkit:7.0.2.
         > Could not get resource 'https://maven.sk89q.com/repo/com/sk89q/worldguard/worldguard-bukkit/7.0.2/worldguard-bukkit-7.0.2.pom'.
            > Could not HEAD 'https://maven.sk89q.com/repo/com/sk89q/worldguard/worldguard-bukkit/7.0.2/worldguard-bukkit-7.0.2.pom'.
               > Read timed out
   > Could not resolve co.aikar:acf-paper:0.5.0-SNAPSHOT.
     Required by:
         project :base
      > Could not resolve co.aikar:acf-paper:0.5.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.sk89q.com/repo/co/aikar/acf-paper/0.5.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://maven.sk89q.com/repo/co/aikar/acf-paper/0.5.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://maven.sk89q.com/repo/co/aikar/acf-paper/0.5.0-SNAPSHOT/maven-metadata.xml'.
                  > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s

------

**Comment by bristermitten** [comment]
This seems to be an issue with the WorldEdit/WorldGuard repository and not really something I can fix, sorry. Furthermore this project is more or less abandoned.

However, if you have a bit of Gradle knowledge, you could try downloading the jars manually and putting them in `base/lib`, in the same way things like AutoSellAPI are depended on
